- name: Install required packages
  hosts: all
  become: yes
  tasks:
    - name: Update the package index
      apt:
        update_cache: yes
      tags: update-packages

    - name: Install wget, tasksel, and python3
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - tasksel
        - python3
        - python3-pip
      tags: installation

   
